# Generated by Django 6.0.2 on 2026-03-04 11:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_sender_message_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSwitchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactivity_days', models.PositiveIntegerField(default=30)),
                ('cooling_off_days', models.PositiveIntegerField(default=7)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COOLING_OFF', 'Cooling Off'), ('RELEASED', 'Released')], default='ACTIVE', max_length=20)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cooling_started_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='switch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
